#!/bin/bash

repo="$(iai repo)" || exit
cd "$repo" || exit

node test/exports.js || exit
node test/raw-through.js || exit

node test/sigint-default.js || exit
node test/sigint-number.js || exit
node test/sigint-array.js || exit

node test/timeout.js || exit
node test/timeout-refresh.js || exit
node test/timeout-unpipe.js || exit
node test/timeout-error.js || exit

node test/tty-rawmode.js || exit
node test/tty-rawmode-trap.js || exit
node test/tty-rawmode-error.js || exit

{
  TEST=(timeout --foreground 1 node test/stdin-pause.js)
  echo TEST "${TEST[*]}"
  "${TEST[@]}"
  CODE=$?
  (( $CODE )) \
    && echo "FAIL test did not complete" \
    || echo "PASS test run ends with code 0"
  echo CODE $CODE
  (( $CODE )) && exit $CODE
}

{
  echo "TEST standard --fix"
  standard --fix
  code=$?
  (( $code )) \
    && echo "FAIL standard linter reported errors" \
    || echo "PASS standard linter did not report errors"
  echo "CODE $code"
  exit $code
}
