#!/bin/bash

repo="$(iai repo)" || exit
cd "$repo" || exit

node test/exports.js || exit
node test/raw-through.js || exit

{
  echo "TEST standard --fix"
  standard --fix
  code=$?
  (( $code )) \
    && echo "FAIL standard linter reported errors" \
    || echo "PASS standard linter did not report errors"
  echo "CODE $code"
  exit $code
}
